export interface Welcome {
  id:number,
  welcome_titre_fr:string,
  welcome_titre_en:string,
  welcome_msg_fr:string,
  welcome_msg_en:string,
  photo:File,
  welcome_keyword_en:string,
  welcome_keyword_fr:string,
  welcome_description_en:string,
  welcome_description_fr:string,
  welcome_titre_fr_slug :string,
  welcome_titre_en_slug :string,
  meta_description_fr :string,
  meta_description_en :string,
}

export interface Medecin {
  id:number,
  doc_titre_fr:string,
  doc_titre_en:string,
  doc_msg_fr:string,
  doc_msg_en:string,
  photo:File,
  doc_keyword_en:string,
  doc_keyword_fr:string,
  doc_description_en:string,
  doc_description_fr:string,
  doc_titre_fr_slug :string,
  doc_titre_en_slug :string,
  meta_description_fr :string,
  meta_description_en :string,
}
export interface Consultation {
  id:number,
  cons_titre_fr:string,
  cons_titre_en:string,
  cons_msg_fr:string,
  cons_msg_en:string,
  photo:File,
  cons_keyword_en:string,
  cons_keyword_fr:string,
  cons_description_en:string,
  cons_description_fr:string,
  cons_titre_fr_slug :string,
  cons_titre_en_slug :string,
  meta_description_fr :string,
  meta_description_en :string,
}
export interface Electrocardiographie
{
  id:number,
  electrocardiography_titre_fr:string,
  electrocardiography_titre_en:string,
  electrocardiography_msg_fr:string,
  electrocardiography_msg_en:string,
  photo:File,
  electrocardiography_keyword_en:string,
  electrocardiography_keyword_fr:string,
  electrocardiography_description_en:string,
  electrocardiography_description_fr:string,
  electrocardiography_titre_fr_slug :string,
  electrocardiography_titre_en_slug :string,
  meta_description_fr :string,
  meta_description_en :string,
}

export interface Media {
  id: number,
  model_type: string,
  model_id: number,
  uuid: string,
  collection_name: string,
  name: string,
  file_name: string,
  mime_type: string,
  disk: string,
  conversions_disk: string,
  size: number,
  manipulations: [],
  custom_properties: [],
  generated_conversions: [],
  responsive_images: [],
  order_column: number,
  created_at: Date,
  updated_at: Date,
  original_url: string,
  preview_url: string
}
