<?php

namespace App\Notifications;

use Carbon\Carbon;
use Illuminate\Auth\Notifications\VerifyEmail;
use Illuminate\Support\Facades\URL;

class VerifyApiEmail extends VerifyEmail
{
    protected function verificationUrl($notifiable)
    {
        return URL::temporarySignedRoute(
            'verify',
            Carbon::now()->addMinute(60),
            [
                'id'=>$notifiable->getKey()
            ]
        ); // TODO: Change the autogenerated stub
    }

    public function toMail($notifiable)
    {
        return parent::toMail($notifiable); // TODO: Change the autogenerated stub
    }

    public static function toMailUsing($callback)
    {
        //parent::toMailUsing($callback); // TODO: Change the autogenerated stub
        return (new MailMessage)
            ->subject("Confirmation d'adresse e-mail")
            ->line('Cliquez sur le bouton ci-dessous pour vérifier votre adresse e-mail')
            ->action("Vérifier l'adresse e-mail");
    }


}
