<?php

namespace App\Repositories;

use App\Http\Resources\AppointmentResource;
use App\Http\Resources\DoctorResource;
use App\Models\Doctor;
use App\Models\Patient;
use App\Models\Role;
use App\Models\User;
use Carbon\Carbon;

use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Support\Str;


class DoctorRepository extends BaseRepository
{
    protected $userRepository;
    public function __construct(Doctor $doctor)
    {
        $this->model=$doctor;

    }
  public function findWithId($id){
    $doctor=Doctor::with(['user'])
        ->where('id',$id)
        ->get();
    //$doctor= parent::findById($id); // TODO: Change the autogenerated stub
    return DoctorResource::collection($doctor);

}
    public function findById($id)
    {
        return parent::findById($id);
    }

    public function delete($id)
    {
        $doctor=parent::findById($id);;
        User::find($doctor->user_id)->delete();
        return parent::delete($id);
    }

    public function update(array $input, $id)
    {
        $currentDoctor=$this->findWithId($id)->first();
        $input['first_name']=isset($input['first_name'])? Str::title($input['first_name']):$currentDoctor->user->first_name;
        $input['last_name']=isset($input['last_name'])? Str::upper($input['last_name']):$currentDoctor->user->last_name;
        $input['phone_number']=isset($input['phone_number'])? $input["phone_number"]:$currentDoctor->phone_number;
        $input['email']=isset($input['email'])? $input["email"]:$currentDoctor->user->email;
        $input['user_id']=isset($input['user_id'])? $input["user_id"]:$currentDoctor->user_id;
        $input['specialite_id']=isset($input['specialite_id'])? $input["specialite_id"]:$currentDoctor->specialite_id;
        $input['updated_by']=isset($input['updated_by'])? $input["updated_by"]:$currentDoctor->updated_by;
        $input['created_by']=isset($input['created_by'])? $input["created_by"]:$currentDoctor->created_by;


        $user=User::where('email',$input['email'])->first();
        $user->first_name=$input['first_name'];
        $user->last_name=$input['last_name'];
        $user->save();

        //$input['updated_by']=$input['first_name'].' '. $input['last_name'];
        //$input['created_by']=$input['first_name'].' '. $input['last_name'];
        unset($input['first_name']);
        unset($input['last_name']);
        unset($input['email']);
        unset($input['password']);
        //dd($input);
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $input)
    {
        //dd('create');
        $input['first_name']=Str::title($input['first_name']);
        $input['last_name']=Str::upper($input['last_name']);
        $input['password']=bcrypt($input['password']);
        $password=$input['password'];
        $roleName= $input['role'] ?? 'Doctor';

        $user = User::create([
            'first_name'=>$input['first_name'],
            'last_name'=>$input['last_name'],
            'password'=>$input['password'],
            'email'=>$input['email'],
        ]);

        $user->sendApiEmailVerificationNotification();
        $role=Role::where('role',$roleName)->first();
        $user->roles()->attach($role->id);
        //$user= parent::create($input); // TODO: Change the autogenerated stub
        //$user->sendApiEmailVerificationNotification();
        $input['user_id']=$user->id;
        unset($input['password']);
        unset($input['first_name']);
        unset($input['last_name']);
        unset($input['email']);
        $input['created_by']=$user->first_name.' '.$user->last_name;
        $input['updated_by']=$input['created_by'];
        return parent::create($input);
    }
    public function findAll(){
        $doctors =  Doctor::with(['user' => function ($q) {
            $q->whereNull('deleted_at')->orderBy('last_name', 'asc');
        }])->whereNull('deleted_at')
            ->get();
        /*$doctors = Doctor::has('user')->with('user')->get();
        $doctors = Doctor::with('user' , function (Builder $query) {
            $query->orderBy('last_name', 'asc');
        })->get();

        /*$doctors = Doctor::get()->sortBy(function($query)
                {
                    return $query->user->first_name;
                })->all();*/

        return DoctorResource::collection($doctors);
    }

    public function findDoctorAppointments($id){
        return  AppointmentResource::collection(Doctor::find($id)->appointments()->orderBy('appointment_date', 'asc')->get());
    }

    public function getDoctorId($user_id){
        return User::find($user_id)->doctors()->first()->id;
    }

}
